#!/usr/bin/env bash
# Set dynamic prompt
PROMPT="$1"  # Accept the prompt as an argument

# Check if the prompt contains "password" (case insensitive)
if [[ "$PROMPT" =~ [Pp]assword ]]; then
  # Use password mode (masked input) for password prompts
  rofi -dmenu -password -i -p "$PROMPT" \
    -theme $HOME/.config/rofi/template/askpass.rasi
else
  # Don't use password mode for other prompts
  rofi -dmenu -i -p "$PROMPT" \
    -theme $HOME/.config/rofi/template/askpass.rasi
fi
